sudo: required

language: elm
node_js: '10' # latest 10.x

elm-test: 0.19.0-rev6
elm-format: 0.8.1

cache:
  yarn: true
  directories:
    - node_modules


script:
  - git clone -b master --single-branch https://github.com/justgook/platformer.git ./engine
  - elm-format --validate . && elm-test
  - elm make ./src/Main.elm --optimize --output=./gh-pages/bundle.js

after_success:
  - uglifyjs ./gh-pages/bundle.js --compress "pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters,keep_fargs=false,unsafe_comps,unsafe" | uglifyjs --mangle --output=./gh-pages/bundle.js
#  - uglifyjs ./node_modules/highlight.js/lib/highlight.js ./node_modules/highlight.js/lib/languages/elm.js  ./gh-pages/bundle.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters' --output=./gh-pages/bundle.js && prepack ./gh-pages/bundle.js --inlineExpressions | uglifyjs --compress 'keep_fargs=false,unsafe_comps,unsafe' --mangle --output=./gh-pages/bundle.js
  - git clone -b assets --single-branch https://github.com/$TRAVIS_REPO_SLUG.git ./gh-pages/assets
  - mkdir ./gh-pages/highlight.js

  - mv node_modules/highlight.js/styles/github.css ./gh-pages/highlight.js/styles/github.css
  - mv node_modules/highlight.js/lib/highlight.js ./gh-pages/highlight.js/lib/highlight.js
  - mv node_modules/highlight.js/lib/languages/elm.js ./gh-pages/highlight.js/lib/languages/elm.js
  - mv node_modules/highlight.js/lib/languages/glsl.js ./gh-pages/highlight.js/lib/languages/glsl.js



deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: gh-pages
  on:
    branch: master
